force-app/main/default/objects/FSTriggerConfig__c/FSTriggerConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Centralized place where we have all the Forms to enable the Auto-Generate Prefill Link.</description>
    <label>FSTriggerConfig</label>
</CustomObject>

force-app/main/default/objects/FSTriggerConfig__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <description>URL Field which we will set the link for Prefill the Form.</description>
    <label>FieldApiName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FSTriggerConfig__c/fields/ObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName__c</fullName>
    <description>This custom settings you can have many forms for one Object. This will help filter all the forms for a specific trigger.</description>
    <label>ObjectAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSCustomAutoGeneratePrefillLinkTest.cls
@IsTest
public with sharing class FSCustomAutoGeneratePrefillLinkTest {
  @IsTest
  public static void simpleTestForCoverage() {
    /**
     * This code is only to have coverage.
     * Because we don't have a Form with a Prefill, the link won't be generated.
     */

    // Arrange
    string triggerObjectApiName = 'Account';
    string formName = 'Form A';

    Account fakeAccount = new Account(name='fake Account');
    insert fakeAccount;

    FSTriggerConfig__c prefillConfig = new FSTriggerConfig__c();
    prefillConfig.Name = formName;
    prefillConfig.FieldApiName__c = 'Website';
    prefillConfig.ObjectAPIName__c = triggerObjectApiName;
    insert prefillConfig;

    VisualAntidote__Previous_Form__c fakeForm = new VisualAntidote__Previous_Form__c();
    fakeForm.Name = formName;
    fakeForm.VisualAntidote__Draft_Form__c = null;
    insert fakeForm;

    List<FSGeneratePrefillWorkFlowAutomation.FSPrefillParameters> ListOfprefillParameters = new List<FSGeneratePrefillWorkFlowAutomation.FSPrefillParameters>();
    FSGeneratePrefillWorkFlowAutomation.FSPrefillParameters prefillParameters = new FSGeneratePrefillWorkFlowAutomation.FSPrefillParameters();
    prefillParameters.sfRecordId = fakeAccount.id;
    ListOfprefillParameters.add(prefillParameters);
    // Act
    FSGeneratePrefillWorkFlowAutomation.execute(ListOfprefillParameters);

    // Assert
    Assert.isTrue(true, 'The should reash here');
  }
}